variables:
    GIT_DEPTH: 5

stages:
    - build
    - test

build:
    script: docker-compose build
    only:
        - develop

test:
    script: docker-compose up --exit-code-from ygwifi
    only:
        - develop
