variables:
    GIT_DEPTH: 3

stages:
    - Build Development
    - Build Test
    - Run Tests
    - Build
    - Push
    - Deploy

# develop branch

build-dev:
    stage: Build Development
    script: docker-compose up --build -d --build-arg reqs=requirements.test.txt
    tags: [dev]
    only: [develop]

build_test:
    stage: Build Test
    script:
        - docker build . -t ryazbeck/ygwifi:test -f Dockerfile.test
        - . /home/gitlab-runner/ygwifi-test.sh # set env vars
        - docker rm ygwifi-test --force
        - docker run --detach --name ygwifi-test
          --env WIFI_SSID=${WIFI_SSID}
          --env WIFI_KEY=${WIFI_KEY}
          --network=host ryazbeck/ygwifi:test
    tags: [dev]
    only: [develop]

flake8:
    stage: Run Tests
    script: docker exec ygwifi-test flake8 app.py
    tags: [dev]
    only: [develop]

pylint:
    stage: Run Tests
    script: docker exec ygwifi pylint app.py
    tags: [dev]
    only: [develop]

pytest:
    stage: Run Tests
    when: on_success
    script: docker exec ygwifi-test pytest test.py
    tags: [dev]
    only: [develop]

# master branch

build:
    stage: Build
    script: docker-compose build
        --build-arg FLASK_ENV=production
        --build-arg LOG_LEVEL=WARNING
        --build-arg TESTING=False
        --build-arg TAG=latest
    tags: [dev]
    only: [master]

push:
    stage: Push
    when: on_success
    script:
        - . /home/gitlab-runner/ygwifi-test.sh # set env vars
        - docker login --username ryazbeck --password ${DOCKER_PW}
        - docker push ryazbeck/ygwifi:latest
    tags: [dev]
    only: [master]

deploy:
    stage: Deploy
    when: on_success
    script:
        - docker pull ryazbeck/ygwifi:latest
        - docker run ryazbeck/ygwifi:latest
    tags: [prod]
    only: [master]
