variables:
    GIT_DEPTH: 5

stages:
    - build-dev
    - test
    - build-prod
    - push
    - deploy

build-dev:
    script:
        - docker-compose up --build -d
    only:
        - develop

test:
    script:
        - docker build . -t ryazbeck/ygwifi:test -f Dockerfile.test
        - docker run \
          --network=host \
          --env-file /etc/gitlab-runner/ygwifi-test.env \
          --user "$(id -u):$(id -g)" \
          ryazbeck/ygwifi:test
    only:
        - develop

build-prod:
    script: docker-compose build \
        --build-arg FLASK_ENV=production \
        --build-arg LOG_LEVEL=WARNING \
        --build-arg TAG=prod
    only:
        - master

push:
    script: docker push ryazbeck/ygwifi:prod
    only:
        - master
