variables:
    GIT_DEPTH: 3

stages:
    - build-dev
    - test
    - push-dev
    - build-prod
    - push-prod
    - deploy

build-dev:
    script:
        - docker-compose up --build -d
    tags: [dev]
    only: [develop]

test:
    script:
        - docker build . -t ryazbeck/ygwifi:test -f Dockerfile.test
        - docker run
          --network=host
          --env-file /home/gitlab-runner/ygwifi-test.env
          ryazbeck/ygwifi:test
    tags: [dev]
    only: [develop]

push-dev:
    script:
        - docker push ryazbeck/ygwifi:dev
    tags: [dev]
    only: [develop]

build-prod:
    script: docker-compose build
        --build-arg FLASK_ENV=production
        --build-arg LOG_LEVEL=WARNING
        --build-arg TESTING=False
        --build-arg TAG=latest
    tags: [dev]
    only: [master]

push-prod:
    script: docker push ryazbeck/ygwifi:latest
    tags: [dev]
    only: [master]

deploy:
    script:
        - docker pull ryazbeck/ygwifi:latest
        - docker run ryazbeck/ygwifi:latest
    tags: [prod]
    only: [master]
