variables:
    GIT_DEPTH: 5

stages:
    - build-dev
    - test
    - build-prod
    - push
    - deploy

build-dev:
    script:
        - docker-compose up --build -d
    only:
        - develop

test:
    script:
        - pip install pytest
        - pytest src/test.py
    only:
        - develop

build-prod:
    script: docker-compose build \
        --build-arg FLASK_ENV=production \
        --build-arg LOG_LEVEL=WARNING \
        --build-arg TAG=prod
    only:
        - master

push:
    script: docker push ryazbeck/ygwifi:prod
    only:
        - master
