version: "3.8"

services:
    ygwifi:
        build: .
        image: ryazbeck/ygwifi:${TAG:-dev}
        container_name: ygwifi
        volumes:
            - /var/log:/var/log
        network_mode: host
        privileged: true
        ports:
            - 5000:5000
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "2m"
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
        dns:
            - 8.8.8.8
            - 8.8.4.4
        environment:
            FLASK_APP: "app.py"
            FLASK_ENV: "development"
        restart: ${RESTART_POLICY:-always}
