version: "3.8"

services:
  ygwifi:
    container_name: ygwifi
    image: ygwifi:dev
    volumes:
      - /var/log:/var/log
      - /var/run/dbus:/var/run/dbus
    network_mode: host
    privileged: true
    build: ./
